# Generated by Django 2.0.2 on 2018-03-08 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Architecture')),
            ],
        ),
        migrations.CreateModel(
            name='Logiciel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logiciel', models.FileField(upload_to='logiciel')),
                ('version', models.CharField(max_length=100)),
                ('architecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Architecture')),
            ],
        ),
        migrations.CreateModel(
            name='Systeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Systeme')),
            ],
        ),
        migrations.AddField(
            model_name='logiciel',
            name='systeme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Systeme'),
        ),
    ]
