# Generated by Django 2.0.4 on 2018-05-25 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='logiciel',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Version'),
        ),
    ]
