# Generated by Django 2.0.4 on 2018-05-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0002_auto_20180525_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
