# Generated by Django 2.0.4 on 2018-05-27 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0003_auto_20180525_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='logiciel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
