# Generated by Django 2.0.4 on 2018-05-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0004_logiciel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='logiciel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
