# Generated by Django 2.0.4 on 2018-05-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0005_logiciel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logiciel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
