# Generated by Django 2.1.1 on 2018-11-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181007_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
